In [1]:
import numpy as np
an_array=np.array([3,33,333])
print(type(an_array))

<class 'numpy.ndarray'>


In [3]:
print(an_array.shape)

(3,)


In [6]:
print(an_array[0],an_array[1],an_array[2])

3 33 333


In [7]:
an_array[0]=888
print(an_array)

[888  33 333]


In [9]:
another=np.array([[11,12,13],[21,22,23]])
print(another)

[[11 12 13]
 [21 22 23]]


In [10]:
print(another.shape)

(2, 3)


In [12]:
print(another[0,0],another[0,1],another[1,0])

11 12 21


In [19]:
ex1=np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [15]:
ex2=np.full((3,3),9.0)
print(ex2)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [17]:
ex3=np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [21]:
ex4=np.ones((2,1))
print(ex4)

[[1.]
 [1.]]


In [30]:
ex4.shape


(2, 1)

In [29]:
print(ex4[0,0])

1.0


In [28]:
ex5=np.random.random((2,2))
print(ex5)

[[0.57276556 0.49435037]
 [0.5244076  0.72904265]]


# Slice Indexing

In [39]:
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [40]:
a_slice=an_array[0:2,1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [41]:
print("Before:",an_array[0,1])

Before: 12


In [42]:
a_slice[0,0]=1000
print("after:",an_array[0,1])

after: 1000


In [52]:
a_slice1=an_array[1,:]
print(a_slice1)

[21 22 23 24]


In [53]:
a_slice2=an_array[1:2,0:4]
print(a_slice2)

[[21 22 23 24]]


In [54]:
a_slice1.shape

(4,)

In [55]:
a_slice2.shape

(1, 4)

In [57]:
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [59]:
row_rank1=an_array[1,:]
print(row_rank1,row_rank1.shape)

[21 22 23 24] (4,)


In [60]:
row_rank2=an_array[1:2,:]
print(row_rank2,row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [61]:
column_rank1=an_array[:,1]
print(column_rank1,column_rank1.shape)

[12 22 32] (3,)


In [62]:
column_rank2=an_array[:,1:2]
print(column_rank2,column_rank2.shape)

[[12]
 [22]
 [32]] (3, 1)


In [63]:
an_array=np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [64]:
col_indices=np.array([0,1,2,0])
print('\ncol indices picked  :',col_indices)


col indices picked  : [0 1 2 0]


In [66]:
row_indices=np.arange(4)
print('\n Row indices picked :',row_indices)


 Row indices picked : [0 1 2 3]


In [67]:
for i,j in zip(row_indices,col_indices):
    print(i,',',j)

0 , 0
1 , 1
2 , 2
3 , 0


In [68]:
print('Values in the array at thode indices:  ',an_array[row_indices,col_indices])

Values in the array at thode indices:   [11 22 33 41]


In [70]:
an_array[row_indices,col_indices]+=10000
print('\nChanged Array:')
print(an_array)


Changed Array:
[[20011    12    13]
 [   21 20022    23]
 [   31    32 20033]
 [20041    42    43]]


# Boolean Indexing

In [2]:
import numpy as np


In [72]:
an_array=np.array([[11,12],[21,22],[31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [74]:
filter=(an_array>15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [75]:
print(an_array[filter])

[21 22 31 32]


In [77]:
print(an_array[an_array>15])

[21 22 31 32]


In [78]:
an_array[an_array%2==0]+=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


In [79]:
ex1=np.array([11,12])
print(ex1.dtype)

int32


In [80]:
ex2=np.array([11.1,12.0])
print(ex2.dtype)

float64


In [81]:
ex3=np.array([11,21],dtype=np.int64)
print(ex3.dtype)

int64


In [82]:
ex4=np.array([11,21],dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 21]


In [83]:
ex5=np.array([11,21],dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


In [3]:
import numpy as np
x=np.array([[111,112],[121,122]],dtype=np.int)
y=np.array([[211.1,212.1],[221.1,222.1]],dtype=np.float64)
print(x)
print()
print(y)
        

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [85]:
print(x+y)
print()
print(np.add(x,y))

[[322.1 324.1]
 [342.1 344.1]]
[[322.1 324.1]
 [342.1 344.1]]


In [86]:
print(x-y)
print()
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [87]:
print(x*y)
print()
print(np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [88]:
print(x/y)
print()
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [89]:
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [90]:
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [92]:
arr=10*np.random.randn(2,5)
print(arr)

[[-11.71262361   1.10907637  -6.94200847   9.39733233  -6.99246357]
 [ -0.30020067   9.32082047  -0.50423025   4.61752119 -17.99753957]]


In [93]:
print(arr.mean())

-2.000431576701053


In [94]:
print(arr.mean(axis=1))#mean by row

[-3.02813739 -0.97272576]


In [95]:
print(arr.mean(axis=0))#mean by column

[ -6.00641214   5.21494842  -3.72311936   7.00742676 -12.49500157]


In [96]:
print(np.median(arr,axis=1))

[-6.94200847 -0.30020067]


In [97]:
print(np.median(arr,axis=0))

[ -6.00641214   5.21494842  -3.72311936   7.00742676 -12.49500157]


In [98]:
unsorted=np.random.randn(10)
print(unsorted)

[ 0.59914202  0.11710516  0.99498964 -2.00810757 -0.343067   -0.44157408
 -0.12247826  0.01907455  1.33812055 -2.6337567 ]


In [99]:
sorted=np.array(unsorted)
sorted.sort()
print(sorted)
print()
print(unsorted)

[-2.6337567  -2.00810757 -0.44157408 -0.343067   -0.12247826  0.01907455
  0.11710516  0.59914202  0.99498964  1.33812055]

[ 0.59914202  0.11710516  0.99498964 -2.00810757 -0.343067   -0.44157408
 -0.12247826  0.01907455  1.33812055 -2.6337567 ]


In [100]:
unsorted.sort()
print(unsorted)

[-2.6337567  -2.00810757 -0.44157408 -0.343067   -0.12247826  0.01907455
  0.11710516  0.59914202  0.99498964  1.33812055]


In [101]:
array=np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


In [ ]:
#10/05/2021

In [4]:
s1=np.array(['desk','chair','bulb'])
s2=np.array(['lamp','bulb','chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [14]:
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [13]:
print(np.union1d(s1,s2) )

['bulb' 'chair' 'desk' 'lamp']


In [15]:
print(np.setdiff1d(s1,s2))#element in s1 that are not in s2

['desk']


In [16]:
print(np.in1d(s1,s2))#element of s1 is also in s2

[False  True  True]


In [3]:
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
add_rows=np.array([1,0,2])
print(add_rows)

[1 0 2]


In [5]:
y=start + add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [7]:
add_cols=np.array([[0,1,2,3]])
add_cols=add_cols.T #transpose
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [8]:
y=start+add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [9]:
add_scalar=np.array([1])
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
arrA=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
arrB=[0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [12]:
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


In [32]:
from numpy import arange
from timeit import Timer

size=1000000
timeits=1000

In [33]:
nd_array=arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>


In [35]:
timer_numpy=Timer("nd_array.sum()", "from __main__ import nd_array")
print("Time taken by numpy ndarray: %f seconds" %
     (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.001007 seconds


In [37]:
a_list=list(range(size))
print(type(a_list))

<class 'list'>


In [38]:
timer_list=Timer("sum(a_list)", "from __main__ import a_list")
print("Time taken by list: %f seconds" %
     (timer_list.timeit(timeits)/timeits))

Time taken by list: 0.065953 seconds


In [13]:
#11/05/2021

In [14]:
import numpy as np
x=np.array([23,23,24,24,])

In [15]:
np.save('an_array',x)#saves the value in x to an_array

In [16]:
np.load('an_array.npy')

array([23, 23, 24, 24])

In [19]:
np.savetxt('array.txt',X=x,delimiter=',')#savetxt function will store your file in text format.
np.loadtxt('array.txt',delimiter=',')#delimiter and sep are same which is separated by comma

array([23., 23., 24., 24.])

In [20]:
x2d=np.array([[1,1],[1,1]])
y2d=np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d,y2d))#dot product of two matrices

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [21]:
a1d=np.array([9,9])
b1d=np.array([10,10])
print(a1d.dot(b1d))
print()
print(np.dot(a1d,b1d))#dot product of vectors

180

180


In [22]:
#dot produce on an array and vector
print(x2d.dot(a1d))
print()
print(np.dot(x2d,a1d))

[18 18]

[18 18]


In [23]:
#sum element in the array
ex1=np.array([[11,12],[21,22]])
print(np.sum(ex1))

66


In [24]:
print(np.sum(ex1,axis=0))#column vise

[32 34]


In [25]:
print(np.sum(ex1,axis=1))#row vise

[23 43]


In [31]:
x=np.random.randn(8)
x

array([ 1.90396672,  0.58070925, -0.46089759, -0.80119449, -1.20715522,
        0.48104697,  0.9656435 , -0.03788706])

In [35]:
y=np.random.randn(8)
y

array([ 1.07784478,  0.37306673, -1.15866942,  0.57716379, -0.64138914,
        1.21622202, -1.35254316, -1.90447581])

In [36]:
import numpy as np
x=np.random.randn(8)
y=np.random.randn(8)
np.maximum(x,y)
print(x)
print(y)
print(np.maximum(x,y))

[ 0.41356363 -0.98335769  2.28493586  0.07816014  1.05203857  0.23585923
 -0.90698071  0.50614665]
[ 0.69419049 -1.52963733  0.29487348  0.09603736 -0.54577222 -0.49686398
  0.76207255 -3.04745994]
[ 0.69419049 -0.98335769  2.28493586  0.09603736  1.05203857  0.23585923
  0.76207255  0.50614665]


In [42]:
#17/05/2021

In [1]:
#Reshapping array:

In [2]:
#grab values from 0 through 19 in array

In [4]:
import numpy as np
arr=np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [5]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [6]:
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [9]:
#transpose
ex1=np.array([[11,12],[21,22]])
ex1.T

array([[11, 21],
       [12, 22]])

In [10]:
x_1=np.array([1,2,3,4,5])
y_1=np.array([11,22,33,44,55])
filter=np.array([True,False,True,False,True])

In [11]:
out=np.where(filter,x_1,y_1)
print(out)

[ 1 22  3 44  5]


In [12]:
mat=np.random.randn(5,5)
mat

array([[ 0.61083954, -0.0623783 ,  0.03875958, -2.26572108,  2.64786763],
       [ 0.89671912,  0.67156388, -1.08090047, -0.72674206,  1.28889388],
       [ 1.41184071, -1.76043685,  0.14664569, -0.4223544 ,  0.09068786],
       [-0.83708874, -0.39275666,  1.37138632,  0.34105355,  1.51777586],
       [ 0.13565563,  0.81378351, -1.39664292, -1.28059105,  0.28146789]])

In [18]:
np.where(mat>0.5,1000,-1)
#if mat>0.5:
#replace(1000)
#else:
#replace(-1)


array([[1000,   -1,   -1,   -1, 1000],
       [1000, 1000,   -1,   -1, 1000],
       [1000,   -1,   -1,   -1,   -1],
       [  -1,   -1, 1000,   -1, 1000],
       [  -1, 1000,   -1,   -1,   -1]])

In [ ]:
#"any" or "all" conditions

In [19]:
arr_bools=np.array([True,False,True,False,True])

In [20]:
arr_bools.any()#is any value true

True

In [21]:
arr_bools.all()# are all values True

False

In [22]:
import numpy as np
Y=np.random.normal(size=(1,5))
print(Y)

[[-1.5606202  -0.57462053 -0.71481087 -0.2815955  -0.28206362]]


In [23]:
Z=np.random.randint(low=2,high=50,size=4)#int interger values
print(Z)

[12 28  6 20]


In [24]:
np.random.permutation(Z)#return a new ordering of element in Z

array([20,  6, 28, 12])

In [25]:
np.random.uniform(size=4)#uniform distribution

array([0.41833229, 0.50133853, 0.68459239, 0.33595307])

In [26]:
np.random.normal(size=4)#normal distribution

array([-1.68932292,  2.17761371, -0.16797166, -0.15672412])

In [27]:
#Merging 

In [31]:
K=np.random.randint(low=2,high=50,size=(2,2))
print(K)
print()
M=np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[27 24]
 [35 28]]

[[47 42]
 [24 45]]


In [32]:
np.vstack((K,M))# Join vertically

array([[27, 24],
       [35, 28],
       [47, 42],
       [24, 45]])

In [34]:
np.hstack((K,M))#Join horizontally

array([[27, 24, 47, 42],
       [35, 28, 24, 45]])

In [35]:
np.concatenate([K,M],axis=0)

array([[27, 24],
       [35, 28],
       [47, 42],
       [24, 45]])

In [40]:
np.concatenate([K,M.T],axis=1)



array([[27, 24, 47, 24],
       [35, 28, 42, 45]])

In [41]:
np.concatenate([K,M],axis=1)

array([[27, 24, 47, 42],
       [35, 28, 24, 45]])